### ISSUE TITLE
Chapter structure

### ISSUE THREAD

**Issue by guilhermejacob** [guilhermejacob/context#1]
@ajdamico and @DjalmaPessoa, what do you think about the current chapter structure? [Page 3](https://github.com/guilhermejacob/context/blob/master/docs/context.pdf).

**Comment by ajdamico** [comment]
fine with me..  @DjalmaPessoa  ?

**Comment by DjalmaPessoa** [comment]
Just a point: there are some funtions that are auxiliary. For instance: svyquantile and svyisq. They are not indeces. They were used to build the estimates and se for more complex indeces.

**Comment by ajdamico** [comment]
should the book even mention them, then?

**Comment by DjalmaPessoa** [comment]
Perhaps not. These functions are used with the function contrastinf to
derive the estimates and se of functions of  quantiles and totals in lower
and upper tails

**Comment by ajdamico** [comment]
probably good to remove anything that an average user isn't expected to use?

**Comment by DjalmaPessoa** [comment]
Is the Gini index there?

**Comment by DjalmaPessoa** [comment]
Are you against writting any formula in the book? Like the index definition?

**Comment by ajdamico** [comment]
section 5.3.1

**Comment by ajdamico** [comment]
i am more interested in presenting reproducible examples that users can apply to their own survey data sets, but i might be outnumbered ;)

**Comment by DjalmaPessoa** [comment]
How about the FGT index? The list is not complete.

There are already reproducible examples in the library documentation? I
believe it should be more than that.

I don't know what the average user means? Can you define it?

**Comment by guilhermejacob** [comment]
The Gini index is in section 5.3.1 (which doesn't appear in the content list). 
The list of all topics in ch. 5 is [here ](https://github.com/guilhermejacob/context/blob/master/04-inequality.Rmd).
And, yes, I forgot the `svyfgt`! i'll add it to the list

**Comment by ajdamico** [comment]
yes, good catch on svyfgt.  when i say average user, i'm talking about
people who are interested in the results but not the math behind them

**Comment by DjalmaPessoa** [comment]
you mean average users  like black boxes.

I believe it is important to define well the measures covered in the
library so that the user can understand well the functions arguments.

 There are two ways of doing this: to write a simple formula or to write a
thousand words to explain the measure. I'm in favor of the first option.

Of course it doesn't make sense to write technical details about
linearization.

**Comment by guilhermejacob** [comment]
I agree with Djalma: well explained mathematical formulas are a good way to convey information to the usual reader. But writing a little bit won't hurt either; this way, we ensure that the not-so-mathematical reader can also benefit.

At this point, I believe we are focused in replicating published results, right? We can make each function section to be a (brief?) theoretical exposition subsection, followed by a replication subsection.

**Comment by ajdamico** [comment]
i'm ok with this so long as my role is limited to programming tasks like replication scripts  :)

**Comment by DjalmaPessoa** [comment]
it is not clear to me the way I should proceed to participate.
I've cloned the context folder to my computer using the desktop git. Should
I use a devtools function to install it? I know it is not a package.
Does it work like  convey? Just change and synch?
To start doing anything I need to know that, so I need some help.

**Comment by ajdamico** [comment]
rstudio has a "build this book" button but you will need to install this
first   http://www.texts.io/support/0002/

**Comment by DjalmaPessoa** [comment]
The Miktex is already isntaled in my computer. Do I have to install it
again. I work all the time with Latex and pdf and everything is working
fine.

**Comment by ajdamico** [comment]
try to "build the book"  if that works, you are good.  otherwise use the
link i sent, it includes some instructions that you may need to follow

**Comment by DjalmaPessoa** [comment]
after "build and reloading" from Rstudio I got: .... DONE (placeholder)

**Comment by ajdamico** [comment]
open up the context.pdf in the /docs/ folder..does it look correct?
