### ISSUE TITLE
wellbeing measures

### ISSUE THREAD

**Issue by guilhermejacob** [guilhermejacob/context#11]
I'm not sure about this title.
I would put something like "Other social indices".
And `svyqsr` is an inequality measure, so I guess i can move it to chapter 3.
What do you think?

**Comment by ajdamico** [comment]
no preference from me

**Comment by guilhermejacob** [comment]
maybe something like "auxiliary functions". That way, we can explain `svyrmir`, `svyiqalpha`, `icdf`, `densfun`, etc.
I actually could use knowing a bit more on `icdf` in other functions.

**Comment by ajdamico** [comment]
@DjalmaPessoa what do you think

**Comment by DjalmaPessoa** [comment]
svyrmir is already included in the section poverty measures. 
The other mentioned functions are only auxiliary and not worth beeing presented in the book and were created just to avoid command repetition, but are not special in any way.
