### ISSUE TITLE
berger bibtex entry

### ISSUE THREAD

**Issue by ajdamico** [guilhermejacob/context#4]
djalma, at the very very bottom of 

	https://cran.r-project.org/web/packages/convey/vignettes/convey-intro.html

you have the reference
	
	Berger, Y.G. e C.J. Skinner (to be published) - Variance Estimation for a Low-Income Proportion.

i am confused about how to add a bibtex entry for it, because it appears to have been published in 2003 but you say it's not yet published.  what bibtex entry should i use?  thanks

	@article{berger2003,
		author = {Berger, Yves G. and Skinner, Chris J.},
		title = {Variance estimation for a low income proportion},
		journal = {Journal of the Royal Statistical Society: Series C (Applied Statistics)},
		volume = {52},
		number = {4},
		publisher = {Blackwell Publishing},
		issn = {1467-9876},
		url = {http://dx.doi.org/10.1111/1467-9876.00417},
		doi = {10.1111/1467-9876.00417},
		pages = {457--468},
		keywords = {Calibration, Complex sampling design, Linearization, Poverty, Quantile, Raking, Survey weight},
		year = {2003},
	}

**Comment by DjalmaPessoa** [comment]
It is already published. I used a Tech Report from Southhampton University
that was published before. You should cite the Journal refernce instead.

**Comment by DjalmaPessoa** [comment]
How can I see what was done so far?

**Comment by ajdamico** [comment]
hi, live website is  https://guilhermejacob.github.io/context/

you can view the github commits to the book here
https://github.com/guilhermejacob/context/commits/master

**Comment by ajdamico** [comment]
the berger reference has been added to the bottom of index.Rmd

https://github.com/guilhermejacob/context/commit/85f8bbce79343199093582111f7f703ffcc690f0
