### ISSUE TITLE
Equivalised Income

### ISSUE THREAD

**Issue by DjalmaPessoa** [guilhermejacob/context#5]
Many examples used in convey are based on equivalised income.from EUSILC data This gives different weights to the people in a Household. As far as I know, this is not used by the people at IBGE.  It might be interesting to use that with brazilian data for the first time. I believe it is possible to do that with the available information.

**Comment by guilhermejacob** [comment]
Sure! Here's an [OECD comment](https://www.oecd.org/eco/growth/OECD-Note-EquivalenceScales.pdf) on equivalence scales, just to present other options.
