### ISSUE TITLE
a few questions/cleanups for djalma?  thanks

### ISSUE THREAD

**Issue by ajdamico** [guilhermejacob/context#9]
https://github.com/guilhermejacob/context/search?utf8=%E2%9C%93&q=djalmapessoa_look

**Comment by ajdamico** [comment]
@DjalmaPessoa could you look at these before we send convey `0.2.0` to cran?  thanks

**Comment by DjalmaPessoa** [comment]
the question:
do any of the other functions need to be moved to this wellbeing chapter?
could have a better answer from Guilherme. 
The important thing is to include all major functions somewhere.

**Comment by ajdamico** [comment]
@guilhermejacob
